### DISCUSSION TITLE
How to use the "extended" payload information

### DISCUSSION THREAD

**Discussion by MrGibbage** [TD22057/insteon-mqtt#319] [Q&A] [answered]
My first time seeing this "discussion" part of github too!

So far, my experience with insteon-mqtt (for that matter, anything with mqtt) has been limited to some node-red flows and some entries in my configuration.yaml that look like this:
```
light:
  - platform: mqtt
    schema: json
    brightness: true
    command_topic: 'insteon/57.a1.28/level'
    state_topic: 'insteon/57.a1.28/state'
    unique_id: 'diningroomchandelier'
    name: 'Dining Room Chandelier'
```
But when I look at the documentation for insteon-mqtt, I see that there seems to be a lot more that I can do. For example, many of the devices (such as dimmers and switches) have a "reason" variable, which I think can be used to figure out if the light came on because of an actual device tap, or a scene, or whatever. I'd like to do that. But when I look at the payload sent when I tap on a light switch, all I see is a state/brightness payload. I'd really like to be able to tell when a switch was physically used so I can use it for triggers.

Specifically, I want to be able to tell when one of the scene buttons has been tapped on a KPL. Is that possible right now?
