### DISCUSSION TITLE
How do I define a scene to turn a switch off?

### DISCUSSION THREAD

**Discussion by MrGibbage** [TD22057/insteon-mqtt#338] [Q&A] [answered]
Responder dimmers can have an on_level: NN attribute. What about a responder ON-OFF switch? I have a movie scene where I want to turn a wall switch off when the scene is turned on. I tried on_level: 0 but it doesn't seem to be working.

**Comment by krkeegan** [comment]
This is using a scene definition in scenes.yaml?

**Comment by MrGibbage** [comment, marked as answer]
Yes, that's what I would like to do
```
  - name: movie
    responders:
      - kitchen_fl:
          on_level: 0
      - fam_room:
          on_level: 20
      - hall:
          on_level: 0.0
    controllers:
      - modem: 26
      - hall kpl: 5
```
kitchen_fl is an ON-OFF switch. It seems on_level is a weird term to use for a switch, but if on_level: 0 should work, then I may have a problem with something else.

**Reply by krkeegan** [reply]
you are correct switches do not have on_levels, their "on" state is stored in data_1.  Try this:

```
  - name: movie
    responders:
      - kitchen_fl:
          data_1: 0
      - fam_room:
          on_level: 20
      - hall:
          on_level: 0.0
    controllers:
      - modem: 26
      - hall kpl: 5
```
