### DISCUSSION TITLE
Any way to assign a Friendly Name to an entity in HomeAssistant?

### DISCUSSION THREAD

**Discussion by dcj** [TD22057/insteon-mqtt#340] [Q&A] [answered]
With the proper entries in `configuration.yaml` and `insteon-mqtt/config.yaml` I end up with a Home Assistant entity that seems to work fine....

Is there any way to specify the HA "area" that this entity is assigned to?

I understand that I can go into the HA GUI, Entities, find my entity, and at that point assign it to an area, but I'd prefer to configure things in my YAML configs....

**Comment by dcj** [comment, marked as answer]
My current hypothesis is that if there is way to do this, it would be via something like:
```
homeassistant:
  customize:
    sensor.digital_input_1:
      friendly_name: "Gate-North"
```
in the home-assistant configuration.yaml file, will try that soon-ish

**Reply by dcj** [reply]
Yes, hypothesis confirmed!  
Added something like this to my configuration.yaml, where ` light.studio_light_rear` is the entity ID of one of my Insteon devices that has been integrated into home-assistant via insteon-mqtt.
```
homeassistant:
  customize:
    light.studio_light_rear:
      friendly_name: "Rear Lights"
```
