### DISCUSSION TITLE
How to update from 0.8.2 to 1.1.1 (or later)?

### DISCUSSION THREAD

**Discussion by dcj** [TD22057/insteon-mqtt#468] [Q&A] [answered]
I've been running 0.8.2 in my Home Assistant for some time, and would like to update to the latest version, but not quite sure how....

Currently my `insteon-mqtt/config.yaml` defines all my devices, e.g.
```
  devices:
    battery_sensor:
      - 32.91.5d: door-ground-level-bathroom
    io_linc:
      - 39.a2.1a: io-rack-lv-power-supply-fan
    dimmer:
      - 21.8c.bb: light-espresso-cart
    outlet:
      - 38.f5.66: outlet-fountain
    switch:
      - 38.66.2f: light-exterior-front
```
And in my HA `configuration.yaml` I have lots of entries like this:
```
light:
  - platform: mqtt
    schema: json
    name: Light-Ground-Level-Bathroom
    unique_id: 28.d2.f7
    brightness: true
    state_topic: insteon/28.d2.f7/state
    command_topic: insteon/28.d2.f7/level
```
And then in `automations.yaml` I have things like this:
```
- id: '1613008048708'
  alias: Basement Storage Lights - On
  description: ''
  trigger:
  - platform: mqtt
    topic: insteon/2b.0f.26/state
    payload: 'ON'
  condition: []
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.lights_2
  mode: single
```
Questions:

1. How do I actually update this Add-on?  Currently I have Auto-update set to off, if I turn it on, is that all I need?
2. Will my existing configs still work, or will I need to redo them all?
