### DISCUSSION TITLE
RFC: Device-level discovery overrides

### DISCUSSION THREAD

**Discussion by kpfleming** [TD22057/insteon-mqtt#483] [Ideas]
As I get deeper into using MQTT Discovery for my devices, I find that I'd like to be able to 'inject' device-level details into the discovery configuration. For example, HA supports setting the `icon`, and setting a `suggested area`, among other attributes.

I don't think it would be practical to try to add support for these in a `discovery_class` (via templating) because if the user doesn't provide a value the config object would end up with an empty attribute.

This *can* be done by creating a discovery_class for each device, but that's a large amount of work and it also means that changes to the base discovery classes in newer versions of insteon-mqtt would have to be merged by hand into those customized versions.

Instead, I think a 'merging' strategy, as used already elsewhere, might make sense.

### Proposal

1. Give names (keys) to the objects in the `discovery_entities` list so that they can be referred to from device configuration. This would be especially important for keypad_linc which generates a large number of entities. Example of `switch`:

```yaml
discovery_entities:
  switch:
    component: 'switch'
    config: |-
      {
        "uniq_id": "{{address}}_switch",
        "name": "{{name_user_case}}",
        "avty_t": "{{availability_topic}}",
        "cmd_t": "{{on_off_topic}}",
        "stat_t": "{{state_topic}}",
        "device": {{device_info_template}},
        "json_attr_t": "{{state_topic}}",
        "json_attr_tpl": "{%- raw -%}
        { \"timestamp\" : {{value_json.timestamp}}, \"mode\" : \"{{value_json.mode}}\", \"reason\" : \"{{value_json.reason}}\" }
        {%- endraw -%}",
        "val_tpl": "{% raw %}{{value_json.state}}{% endraw %}"
      }
```

2. Device configuration:

```yaml
devices:
  switch:
    - aa.bb.cc: "Switch (normal)"
    - dd.ee.ff: "Switch (coffee maker)"
      discovery_details:
        device:
          sa: "Kitchen"
        switch:
          config:
            icon: "mdi:coffee-maker"
```

3. When the discovery config is being composed to send over MQTT, any keys in `discovery_details` would replace identical keys in the discovery_class (with special handling for `config` since it is an 'embedded' object) *before* templating happens. Any new keys provided would be added in their respective locations. The 'device' section would be used to modify the details provided by the `device_info_template` which apply to all entities for that device.

I can envision other 'features' of this as well, such as suppressing default entities (so a 6-button KPL won't generate entities for buttons 2, 7, and 8). My goal here is to provide the maximum amount of detail through MQTT Discovery, and avoid having to override/change details in HA itself after the devices/entities have been discovered by the integration (which means that if they need to be removed and rediscovered the details would not be lost).

All feedback very welcome... and for avoidance of doubt, I'm happy to implement this.
