### DISCUSSION TITLE
Question about scenes

### DISCUSSION THREAD

**Discussion by johnsturgeon** [TD22057/insteon-mqtt#493] [Q&A] [answered]
I really don't want to be a burden, I'm trying desperately to get this to work. I've got a PLM (usb) and I'm trying to set up a few scenes.

Question 1:
I imported the existing scenes and got this:
```yaml
 - controllers:
      - modem:
          group: 254
          data_1: 1
          data_2: 33
          data_3: 65
    responders:
      - anns lamp:
          ramp_rate: 0.3
      - johns lamp:
          on_level: 0.0
          ramp_rate: 0.5
      - 3f.46.34
      - 3f.0c.bc
      - 1c.53.a5
      - 1c.54.23
      - kitchen keypad: 1
      - under counter south
      - anns desk:
          ramp_rate: 0.5
      - kitchen overhead (secondary):
          ramp_rate: 0.5
      - kitchen overhead (main):
          ramp_rate: 0.5
      - under counter north:
          on_level: 58.8
          ramp_rate: 0.5
      - under counter west:
          on_level: 46.3
          ramp_rate: 0.5
      - main lights:
          on_level: 99.6
          ramp_rate: 0.5
      - 14.90.b4
      - porch light:
          on_level: 23.1
          ramp_rate: 0.3
      - foyer chandelier:
          on_level: 0.0
          ramp_rate: 0.5
      - foyer chandelier (upstairs):
          on_level: 0.0
          ramp_rate: 0.5
      - bathroom keypad: 1
      - shower lights:
          on_level: 0.0
          ramp_rate: 0.3
      - main fan:
          data_1: 0
          data_2: 28
      - chandelier:
          on_level: 0.0
          ramp_rate: 0.3
      - bedroom photo nook light:
          on_level: 0.0
          ramp_rate: 0.5
      - 29.06.fb
      - johns closet:
          ramp_rate: 0.5
          data_3: 0
      - toilet room fan:
          data_1: 0
          data_2: 28
      - toilet room light:
          on_level: 0.0
          ramp_rate: 0.5
      - hairdryer outlet:
          data_3: 0
```

I'm not even sure what that means as far as 'scenes' go.  For instance, why is "John's Lamp" on_level set to 0?  
Q: Can I modify that and run a 'sync' and update the modem?  I tried, and it didn't seem to do anything.

---
Second question: 
How can I define an additional scene for my 'button A' on my kitchen keypad to turn on / off my under counter lights?  I added 
```
- name: Kitchen Counter Lights
  responders:
    - under counter north
    - under counter south
    - under counter west
  controllers:
    - kitchen keypad: 3
```
ran `sync-all` and it did nothing

Thanks for any help

**Comment by kpfleming** [comment]
Did you run `sync-all --run` or just `sync-all`? Without `--run` it's just a 'dry run' to show you the changes that would be made.

**Reply by johnsturgeon** [reply]
I want to circle back on this question.

I factory reset the modem, and all my devices (yes.. what a pain).  I re-linked all my devices, and re-created all the links using Indigo software.  Disconnected from my Mac, and reconnected to the HA machine.

I imported-all, and I don't even see the scene I just created

Here is the scene in Indigo (it's a 'group' scene defined in the PowerLinc)
<img width="625" alt="image" src="https://user-images.githubusercontent.com/9746310/156905794-af0cacbd-1347-4614-8664-0e4ef9516ea1.png">

Here is the print-db for the modem
```
>>>insteon-mqtt config.yaml print-db modem
Commanding Modem device 44.86.3b (modem) cmd=print_db
44.86.3b modem database
ModemDb:
  ID: 13.8a.4c (family room: sc grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 13.8a.4c (family room: sc grp: 254 type: CTRL  data: 0x01 0x19 0x38
  ID: 1a.6d.f3 (bathroom: haird grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 1a.6d.f3 (bathroom: haird grp: 254 type: CTRL  data: 0x02 0x08 0x38
  ID: 1c.53.a5 (remote: switch  grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 1c.53.a5 (remote: switch  grp: 254 type: CTRL  data: 0x00 0x11 0x36
  ID: 1c.54.23 (remote: switch  grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 1c.54.23 (remote: switch  grp: 254 type: CTRL  data: 0x00 0x11 0x36
  ID: 20.e9.74 (family room: an grp:   1 type: RESP  data: 0x03 0x1f 0x00
  ID: 20.e9.74 (family room: an grp:   1 type: CTRL  data: 0x03 0x1f 0x00
  ID: 20.e9.74 (family room: an grp: 254 type: CTRL  data: 0x01 0x21 0x41
  ID: 28.e3.6b (hallway: foyer  grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 28.e3.6b (hallway: foyer  grp: 254 type: CTRL  data: 0x01 0x20 0x41
  ID: 28.e4.59 (outside: porch  grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 28.e4.59 (outside: porch  grp: 254 type: CTRL  data: 0x01 0x20 0x41
  ID: 28.e7.9d (hallway: foyer  grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 28.e7.9d (hallway: foyer  grp: 254 type: CTRL  data: 0x01 0x20 0x41
  ID: 29.06.fb (bedroom: hall t grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 29.06.fb (bedroom: hall t grp: 254 type: CTRL  data: 0x01 0x20 0x41
  ID: 29.be.42 (bathroom: chand grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 29.be.42 (bathroom: chand grp: 254 type: CTRL  data: 0x01 0x20 0x41
  ID: 29.c7.3c (bathroom: showe grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 29.c7.3c (bathroom: showe grp: 254 type: CTRL  data: 0x01 0x20 0x41
  ID: 29.cb.a8 (bedroom: photo  grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 29.cb.a8 (bedroom: photo  grp: 254 type: CTRL  data: 0x01 0x20 0x41
  ID: 29.d7.f0 (bathroom: vanit grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 29.d7.f0 (bathroom: vanit grp: 254 type: CTRL  data: 0x01 0x20 0x41
  ID: 29.d8.01 (bathroom: toile grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 29.d8.01 (bathroom: toile grp: 254 type: CTRL  data: 0x01 0x20 0x41
  ID: 29.e5.f5 (family room: fi grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 29.e5.f5 (family room: fi grp: 254 type: CTRL  data: 0x01 0x20 0x41
  ID: 2a.53.dc (bathroom: toile grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 2a.53.dc (bathroom: toile grp: 254 type: CTRL  data: 0x02 0x2a 0x43
  ID: 2a.72.db (bathroom: main  grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 2a.72.db (bathroom: main  grp: 254 type: CTRL  data: 0x02 0x2a 0x43
  ID: 2b.f4.72 (bedroom: main l grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 2b.f4.72 (bedroom: main l grp: 254 type: CTRL  data: 0x01 0x20 0x41
  ID: 30.64.cb (kitchen: keypad grp:   1 type: RESP  data: 0x03 0x1f 0x00
  ID: 30.64.cb (kitchen: keypad grp:   1 type: CTRL  data: 0x03 0x1f 0x00
  ID: 30.64.cb (kitchen: keypad grp: 254 type: CTRL  data: 0x01 0x42 0x43
  ID: 39.a6.0d (family room: fl grp:   1 type: RESP  data: 0x03 0x1f 0x00
  ID: 39.a6.0d (family room: fl grp:   1 type: CTRL  data: 0x03 0x1f 0x00
  ID: 39.a6.0d (family room: fl grp: 254 type: CTRL  data: 0x01 0x21 0x44
  ID: 39.a7.64 (family room: jo grp:   1 type: RESP  data: 0x03 0x1f 0x00
  ID: 39.a7.64 (family room: jo grp:   1 type: CTRL  data: 0x03 0x1f 0x00
  ID: 39.a7.64 (family room: jo grp: 254 type: CTRL  data: 0x01 0x21 0x44
  ID: 3d.b9.09 (family room: ke grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 3d.b9.09 (family room: ke grp: 254 type: CTRL  data: 0x02 0x2c 0x44
  ID: 3f.0c.bc (remote: 4 scene grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 3f.0c.bc (remote: 4 scene grp: 254 type: CTRL  data: 0x00 0x1b 0x39
  ID: 3f.46.05 (remote: 8 scene grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 3f.46.05 (remote: 8 scene grp: 254 type: CTRL  data: 0x00 0x1a 0x39
  ID: 3f.46.34 (remote: 8 scene grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 3f.46.34 (remote: 8 scene grp: 254 type: CTRL  data: 0x00 0x1a 0x39
  ID: 44.43.61 (kitchen: under  grp:   1 type: RESP  data: 0x03 0x1f 0x00
  ID: 44.43.61 (kitchen: under  grp:   1 type: CTRL  data: 0x03 0x1f 0x00
  ID: 44.43.61 (kitchen: under  grp: 254 type: CTRL  data: 0x01 0x32 0x44
  ID: 46.e0.52 (office: overhea grp:   1 type: RESP  data: 0x03 0x1f 0x00
  ID: 46.e0.52 (office: overhea grp: 254 type: CTRL  data: 0x02 0x2a 0x45
  ID: 48.2b.a5 (kitchen: under  grp:   1 type: RESP  data: 0x03 0x1f 0x00
  ID: 48.2b.a5 (kitchen: under  grp:   1 type: CTRL  data: 0x03 0x1f 0x00
  ID: 48.2b.a5 (kitchen: under  grp: 254 type: CTRL  data: 0x01 0x20 0x45
  ID: 48.2b.f8 (kitchen: anns d grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 48.2b.f8 (kitchen: anns d grp:   1 type: CTRL  data: 0x03 0x1f 0x00
  ID: 48.2b.f8 (kitchen: anns d grp: 254 type: CTRL  data: 0x01 0x20 0x45
  ID: 48.2d.7f (kitchen: overhe grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 48.2d.7f (kitchen: overhe grp: 254 type: CTRL  data: 0x01 0x20 0x45
  ID: 48.2e.79 (kitchen: under  grp:   1 type: RESP  data: 0x03 0x1f 0x00
  ID: 48.2e.79 (kitchen: under  grp:   1 type: CTRL  data: 0x03 0x1f 0x00
  ID: 48.2e.79 (kitchen: under  grp: 254 type: CTRL  data: 0x01 0x20 0x45
  ID: 48.30.ba (kitchen: overhe grp:   1 type: RESP  data: 0x03 0x1f 0x00
  ID: 48.30.ba (kitchen: overhe grp:   1 type: CTRL  data: 0x03 0x1f 0x00
  ID: 48.30.ba (kitchen: overhe grp: 254 type: CTRL  data: 0x01 0x20 0x45
  ID: 48.42.fb (bathroom: johns grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 48.42.fb (bathroom: johns grp: 254 type: CTRL  data: 0x01 0x20 0x45
  ID: 48.53.eb (drews room: ove grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 48.53.eb (drews room: ove grp: 254 type: CTRL  data: 0x02 0x2a 0x45
  ID: 48.55.7c (bathroom: anns  grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 48.55.7c (bathroom: anns  grp: 254 type: CTRL  data: 0x02 0x2a 0x45
  ID: 4a.9c.52 (bathroom: keypa grp:   1 type: RESP  data: 0x00 0x00 0xff
  ID: 4a.9c.52 (bathroom: keypa grp: 254 type: CTRL  data: 0x01 0x42 0x45
GroupMap
  254 -> ['13.8a.4c (family room: sconces)', '1a.6d.f3 (bathroom: hairdryer outlet)', '20.e9.74 (family room: anns lamp)', '28.e3.6b (hallway: foyer light (secondary))', '28.e4.59 (outside: porch light)', '28.e7.9d (hallway: foyer light)', '29.06.fb (bedroom: hall to bath)', '29.be.42 (bathroom: chandelier)', '29.c7.3c (bathroom: shower lights)', '29.cb.a8 (bedroom: photo nook light)', '29.d7.f0 (bathroom: vanity lights)', '29.d8.01 (bathroom: toilet room light)', '29.e5.f5 (family room: fireplace flood)', '2a.53.dc (bathroom: toilet room fan)', '2a.72.db (bathroom: main fan)', '2b.f4.72 (bedroom: main lights)', '30.64.cb (kitchen: keypad)', '39.a6.0d (family room: floor lamp)', '39.a7.64 (family room: johns lamp)', '3d.b9.09 (family room: keypad)', '44.43.61 (kitchen: under counter south)', '46.e0.52 (office: overhead light)', '48.2b.a5 (kitchen: under counter west)', '48.2b.f8 (kitchen: anns desk)', '48.2d.7f (kitchen: overhead (secondary))', '48.2e.79 (kitchen: under counter north)', '48.30.ba (kitchen: overhead (main))', '48.42.fb (bathroom: johns closet)', '48.53.eb (drews room: overhead light)', '48.55.7c (bathroom: anns closet)', '4a.9c.52 (bathroom: keypad)', '1c.54.23 (remote: switch (#1))', '3f.46.34 (remote: 8 scene (#4))', '3f.0c.bc (remote: 4 scene)', '1c.53.a5 (remote: switch (#2))', '3f.46.05 (remote: 8 scene (#3))']
  1 -> ['48.2b.f8 (kitchen: anns desk)', '20.e9.74 (family room: anns lamp)', '39.a6.0d (family room: floor lamp)', '39.a7.64 (family room: johns lamp)', '30.64.cb (kitchen: keypad)', '48.30.ba (kitchen: overhead (main))', '48.2e.79 (kitchen: under counter north)', '44.43.61 (kitchen: under counter south)', '48.2b.a5 (kitchen: under counter west)']

Complete
```

Notice that group 1 contains all the links to the devices in my group above.

`import-scenes modem` gives me nothing that would seem like the scene I created.

**Reply by johnsturgeon** [reply]
For the record, here's the `scenes.yaml`
```yaml
  - controllers:
      - modem:
          group: 254
          data_1: 1
          data_2: 25
          data_3: 56
    responders:
      - 'family room: sconces'
      - 'bathroom: hairdryer outlet'
      - 'family room: anns lamp':
          ramp_rate: 0.5
          data_3: 0
      - 'hallway: foyer light (secondary)'
      - 'outside: porch light'
      - 'hallway: foyer light':
          on_level: 0.0
          ramp_rate: 0.5
          data_3: 0
      - 'bedroom: hall to bath':
          on_level: 0.0
          ramp_rate: 0.5
          data_3: 0
      - 'bathroom: chandelier':
          on_level: 0.0
          ramp_rate: 0.5
          data_3: 0
      - 'bathroom: shower lights':
          on_level: 0.0
          ramp_rate: 0.5
          data_3: 0
      - 'bedroom: photo nook light'
      - 'bathroom: vanity lights':
          on_level: 99.6
          ramp_rate: 0.5
          data_3: 0
      - 'bathroom: toilet room light':
          on_level: 99.6
          ramp_rate: 0.5
          data_3: 0
      - 'family room: fireplace flood':
          on_level: 0.0
          ramp_rate: 0.5
          data_3: 0
      - 'bathroom: toilet room fan'
      - 'bathroom: main fan':
          data_2: 28
          data_3: 0
      - 'bedroom: main lights':
          on_level: 99.6
          ramp_rate: 0.5
          data_3: 0
      - 'kitchen: keypad':
          group: 0
          on_level: 0.0
          ramp_rate: 0.5
      - 'family room: floor lamp':
          ramp_rate: 0.5
          data_3: 0
      - 'family room: johns lamp':
          ramp_rate: 0.5
          data_3: 0
      - 'family room: keypad':
          group: 0
          data_1: 0
          data_2: 28
      - 'kitchen: under counter south':
          on_level: 49.0
          ramp_rate: 0.3
          data_3: 0
      - 'office: overhead light':
          data_2: 28
          data_3: 0
      - 'kitchen: under counter west':
          on_level: 49.0
          ramp_rate: 0.3
          data_3: 0
      - 'kitchen: anns desk':
          on_level: 0.0
          ramp_rate: 0.3
          data_3: 0
      - 'kitchen: overhead (secondary)':
          ramp_rate: 0.5
          data_3: 0
      - 'kitchen: under counter north':
          on_level: 50.2
          ramp_rate: 0.3
          data_3: 0
      - 'kitchen: overhead (main)':
          ramp_rate: 0.5
          data_3: 0
      - 'bathroom: johns closet'
      - 'drews room: overhead light':
          data_1: 0
          data_2: 28
          data_3: 0
      - 'bathroom: anns closet'
      - 'bathroom: keypad': 1
      - 'remote: switch (#1)':
          data_1: 3
          data_3: 0
      - 'remote: 8 scene (#4)':
          data_1: 3
          data_3: 0
      - 'remote: 4 scene'
      - 'remote: switch (#2)':
          data_1: 3
          data_3: 0
      - 'remote: 8 scene (#3)'
 ```
