### ISSUE TITLE
Better understanding of Scene.yaml formatting

### ISSUE THREAD

**Issue by djryan012** [TD22057/insteon-mqtt#191]
Thanks you @krkeegan. This was one major issue for this project and have read your doc on scenes, Im running Hassio and have updated to 7.0 and I initial set startup_refresh to True. I have imported all scenes from the modem using mqtt topic insteon/command/48.ef.b1 and payload { “cmd” : “import_scenes_all”, “dry_run” : true} creating a scene file with all of this. Some of it makes sense but I am really at a loss of how to edit it per the scene example to make it readable since my file put controller before responder with a few random # (31, 28, with modem having high #'s ). Any help would be appreciated understand and thanks again for all your hard work on this project. [My insteon config files](https://github.com/djryan012/homeassistant-config/tree/master/insteon-mqtt)

**Comment by krkeegan** [comment]
So your files are here if anyone else wants to look at them:

https://github.com/djryan012/homeassistant-config/tree/master/insteon-mqtt

You have a perfectly reasonable number of devices, so this shouldn't be too hard.

I guess my main question is, what exactly do you need?  Here are some comments and examples based on your files.  But if you still have questions, please post them.

Comments:
1. I would have named my devices using the names you have in the comments, so Outside_Door not Switch2.  Personal preference, but it can make things easier.
2. You won't need to run import_scenes again, and even if you do, it will try to preserve comments, so you can add them.
3. data_2 has some values (mostly 31).  I think at one point Insteon-mqtt was creating links to non-dimmable devices with data_2 being set to 31 when it is normally 0.  This doesn't matter, don't change them, data_2 is generally the ramp_rate, but switches don't ramp.  Anyways you see some clutter because of that, but you can just ignore it.
4. As to the 240 range group numbers at the bottom, I have a vague recollection that this may have been caused by old code that we no longer use in insteon-mqtt.  Unless you wanted a modem scene that controlled the state of the same button on all of your keypadlincs at once.
5. Finally, there is no reason to clean up any of these oddities.  Don't run sync as some pedantic desire to have things be perfect.  You only need to use sync if you are having an issue or need to add a link.

Examples for how to make your file readable:
1. If you use the configuration editor in Home Assistant, each scene should be foldable.  So you can collapse scenes to only see the thing you are working on.
2. You can add comments anywhere so for example at the start of the file:

```
  # Inside/Outside Door 3-Way Switch
  - controllers:
      - switch2:
          data_2: 31
      - switch1:
          data_2: 31
    responders:
      - switch1:
          data_2: 31
      - switch2:
          data_2: 31
```

3. You can also use the name attribute too:

```
  - name: 'Inside_Outside_3_Way'
    controllers:
      - switch2:
          data_2: 31
      - switch1:
          data_2: 31
    responders:
      - switch1:
          data_2: 31
      - switch2:
          data_2: 31
```

Sorry for the rambling.  If you have a more specific question I can probably be more focused.
