### ISSUE TITLE
Manual Hop Setting Per Device

### ISSUE THREAD

**Issue by krkeegan** [TD22057/insteon-mqtt#271]
It seems like there are instances where the hop count is dramatically asymmetric.  See #242 for a possible example.

Hop count is currently set by a rolling average of the total hops required to reach the plm from the device.  But if sending messages to the device takes more hops, this device will constantly encounter a timeout with a retry.  There is no way to constantly calculate hops to the device.  Either a message makes it or it doesn't, we don't get any reporting of excess hops.

Using excess hops is very bad and will lead to bad things on the network.

Perhaps we could add a per device setting allowing the user to set the min_hops used for the device.

**Comment by krkeegan** [comment]
This would be quite the undertaking to add (it may become easier if changes to the config.yaml structure are made to support MQTT discovery).

Plus I am a little worried about adding this feature, as misuse could lead to a lot of latent issues.

Closing unless it becomes more apparent that this is an issue.

**Comment by krkeegan** [comment]
Reopening, as this still remains an issue at least for one user.

__QUESTION__
What should the config look like?  In all of the example below `switch 2` is defined using the sample extra config.  These are listed in the order of my preference.  Keep in mind, there is very likely to be additional extra config values in the future.

Option 1 - Pro: Clean looking, Cons: Some risk in mis-identifying address as the key is ambiguous
```yaml
devices:
  switch:
    - 11.22.33
    - 22.33.44: 'switch 1'
    - 33.44.55: 'switch 2'
      min_hops: 1
    - 44.55.66: 'switch 3'
```

Option 2 - Pro: No ambiguity, Con: I am certain some users will miss the indentation causing issues.
```yaml
devices:
  switch:
    - 11.22.33
    - 22.33.44: 'switch 1'
    - 33.44.55:
        name: 'switch 2'
        min_hops: 1
    - 44.55.66: 'switch 3'
```

Option 3 - Pro: Address is no longer ambiguous, Cons: a little more verbose for users, plus the address moves away from the key side, making it harder to find when scanning through the list.
```yaml
devices:
  switch:
    - 11.22.33
    - 22.33.44: 'switch 1'
    - addr: 33.44.55
      name: 'switch 2'
      min_hops: 1
    - 44.55.66: 'switch 3'
```
