### ISSUE TITLE
Scenes from modem not triggering

### ISSUE THREAD

**Issue by tommycw1** [TD22057/insteon-mqtt#301]
Trying to use scenes form my modem for the first time from insteon<->MQTT

I have several scenes that I've been using for a long time with the native openHAB insteon bundle.  

One example is group 0x1C or 28.  This is supposed to turn off all of my upstairs lights.

I try sending the following:

`mosquitto_pub -h 192.168.1.200 -p 8883 -i "test-client" -d -t "insteon/modem/scene" -m '{ "cmd" : "on", "group" : 28 }'`

or

`mosquitto_pub -h 192.168.1.200 -p 8883 -i "test-client" -d -t "insteon/modem/scene" -m '{ "cmd" : "off", "group" : 28 }'`

Both result in no change to any of the devices and the following in the log:

2021-01-04 19:03:10 INFO Modem: Modem input command: {'cmd': 'on', 'group': 28}
2021-01-04 19:03:10 INFO Modem: Modem scene 28 on=on
2021-01-04 19:03:10 INFO Protocol: Write message to modem: Modem Scene: grp: 28 cmd: 0x11 0x00
2021-01-04 19:03:10 INFO Protocol: Read 0x61: Modem Scene: grp: 28 cmd: 0x11 0x00 ack: False

I'm noticing the ACK = false.  Any ideas what I'm doing wrong or how to debug this?

**Comment by krkeegan** [comment]
I suspect that group 28 doesn't exist.  it might be a difference in decimal and hexidecimal try `'{ "cmd" : "on", "group" : 0x28 }'`

**Comment by krkeegan** [comment]
oh sorry, I see your commend now about 0x1c.  Hmm, can you run refresh on your modem `refresh modem` and post at least the relevant entries for group 28 or 0x1c?

**Comment by tommycw1** [comment]
Interesting.  It was my understanding that the modem doesn't need have a controller link in its DB to send a group broadcast to a given group, so I don't have a link in my db as you can see below.  That would be a ton of links as I have every device on my 2nd floor that respond to this.

```
ModemDb:
  ID: 00.00.00                  grp:   1 type: RESP  data: 0x00 0x00 0x00
  ID: 00.00.00                  grp:   4 type: RESP  data: 0x00 0x00 0x00
  ID: 20.33.a9 (outside floods) grp:   1 type: RESP  data: 0x00 0x00 0x00
  ID: 20.33.a9 (outside floods) grp:   1 type: CTRL  data: 0x01 0x35 0x43
  ID: 22.e2.64                  grp:   1 type: RESP  data: 0x26 0x72 0x64
  ID: 22.e2.64                  grp:   1 type: CTRL  data: 0x01 0x20 0x41
  ID: 23.11.2b (front porch – f grp:   1 type: RESP  data: 0x01 0x2e 0x41
  ID: 23.11.2b (front porch – f grp:   1 type: CTRL  data: 0x01 0x2e 0x41
  ID: 23.ab.4f (outside side do grp:   1 type: RESP  data: 0x01 0x20 0x41
  ID: 23.ab.4f (outside side do grp:   1 type: CTRL  data: 0x01 0x20 0x41
  ID: 23.c9.3e (downstairs bath grp:   1 type: RESP  data: 0x01 0x20 0x41
  ID: 23.c9.3e (downstairs bath grp:   1 type: CTRL  data: 0x01 0x20 0x41
  ID: 23.ca.ea (upstairs bathro grp:   1 type: RESP  data: 0x00 0x00 0x01
  ID: 23.ca.ea (upstairs bathro grp:   1 type: CTRL  data: 0x01 0x20 0x41
  ID: 28.a4.22 (master bedroom  grp:   1 type: RESP  data: 0x01 0x42 0x43
  ID: 28.a4.22 (master bedroom  grp:   1 type: CTRL  data: 0x01 0x42 0x43
  ID: 28.a4.22 (master bedroom  grp:   3 type: RESP  data: 0x00 0x00 0x03
  ID: 28.a4.22 (master bedroom  grp:   4 type: RESP  data: 0x00 0x00 0x04
  ID: 28.a4.22 (master bedroom  grp:   5 type: RESP  data: 0x00 0x00 0x05
  ID: 28.a4.22 (master bedroom  grp:   6 type: RESP  data: 0x00 0x00 0x06
  ID: 28.a4.22 (master bedroom  grp: 243 type: CTRL  data: 0x00 0x00 0xf3
  ID: 28.a4.22 (master bedroom  grp: 244 type: CTRL  data: 0x00 0x00 0xf4
  ID: 28.a4.22 (master bedroom  grp: 245 type: CTRL  data: 0x00 0x00 0xf5
  ID: 28.a4.22 (master bedroom  grp: 246 type: CTRL  data: 0x00 0x00 0xf6
  ID: 2b.3a.51 (outside plug -  grp:   1 type: RESP  data: 0x01 0x42 0x43
  ID: 2b.3a.51 (outside plug -  grp:   1 type: CTRL  data: 0x01 0x35 0x43
  ID: 2b.9f.fd (living room key grp:   1 type: RESP  data: 0x01 0x42 0x43
  ID: 2b.9f.fd (living room key grp:   1 type: CTRL  data: 0x01 0x42 0x43
  ID: 2b.9f.fd (living room key grp:   3 type: RESP  data: 0x01 0x42 0x43
  ID: 2b.9f.fd (living room key grp:   4 type: RESP  data: 0x01 0x42 0x43
  ID: 2b.9f.fd (living room key grp:   5 type: RESP  data: 0x01 0x42 0x43
  ID: 2b.9f.fd (living room key grp:   6 type: RESP  data: 0x01 0x42 0x43
  ID: 2b.ad.52 (kitchen hall ke grp:   1 type: RESP  data: 0x00 0x00 0x00
  ID: 2b.ad.52 (kitchen hall ke grp:   1 type: CTRL  data: 0x01 0x42 0x43
  ID: 2b.ad.52 (kitchen hall ke grp:   3 type: RESP  data: 0x01 0x42 0x43
  ID: 2b.ad.52 (kitchen hall ke grp:   4 type: RESP  data: 0x01 0x42 0x43
  ID: 2b.ad.52 (kitchen hall ke grp:   5 type: RESP  data: 0x01 0x42 0x43
  ID: 2b.ad.52 (kitchen hall ke grp:   6 type: RESP  data: 0x01 0x42 0x43
  ID: 2b.ad.52 (kitchen hall ke grp: 228 type: CTRL  data: 0x00 0x00 0xe4
  ID: 2b.ad.52 (kitchen hall ke grp: 230 type: CTRL  data: 0x00 0x00 0xe6
  ID: 2b.cc.17 (kitchen recesse grp:   1 type: RESP  data: 0x01 0x20 0x41
  ID: 2b.cc.17 (kitchen recesse grp:   1 type: CTRL  data: 0x01 0x20 0x41
  ID: 2b.cc.17 (kitchen recesse grp:  10 type: CTRL  data: 0x00 0x00 0x0a
  ID: 2b.cc.17 (kitchen recesse grp:  11 type: CTRL  data: 0x00 0x00 0x0b
  ID: 2e.1c.9c (dish washer lea grp:   1 type: RESP  data: 0x00 0x00 0x01
  ID: 2e.1c.9c (dish washer lea grp:   2 type: RESP  data: 0x02 0x2f 0x48
  ID: 2e.1c.9c (dish washer lea grp:   3 type: RESP  data: 0x00 0x00 0x03
  ID: 2e.1c.9c (dish washer lea grp:   4 type: RESP  data: 0x00 0x00 0x04
  ID: 2e.3e.44 (xmas tree)      grp:   1 type: RESP  data: 0x01 0x20 0x45
  ID: 2e.3e.44 (xmas tree)      grp:   1 type: CTRL  data: 0x01 0x0e 0x41
  ID: 32.9f.9a (side door hds – grp:   0 type: CTRL  data: 0x10 0x11 0x45
  ID: 32.9f.9a (side door hds – grp:   1 type: RESP  data: 0x10 0x11 0x45
  ID: 32.9f.9a (side door hds – grp:   1 type: CTRL  data: 0x10 0x11 0x45
  ID: 32.9f.9a (side door hds – grp:   2 type: RESP  data: 0x00 0x00 0x02
  ID: 32.9f.9a (side door hds – grp:   3 type: RESP  data: 0x00 0x00 0x00
  ID: 32.9f.9a (side door hds – grp:   4 type: RESP  data: 0x00 0x00 0x00
  ID: 32.a0.4b (back door hds – grp:   1 type: RESP  data: 0x00 0x00 0x00
  ID: 32.a0.4b (back door hds – grp:   1 type: CTRL  data: 0x10 0x11 0x45
  ID: 32.a0.4b (back door hds – grp:   2 type: RESP  data: 0x00 0x00 0x02
  ID: 32.a0.4b (back door hds – grp:   3 type: RESP  data: 0x00 0x00 0x00
  ID: 32.a0.4b (back door hds – grp:   4 type: RESP  data: 0x00 0x00 0x00
  ID: 32.a0.c7 (front door hds  grp:   0 type: CTRL  data: 0x10 0x11 0x45
  ID: 32.a0.c7 (front door hds  grp:   1 type: RESP  data: 0x00 0x00 0x00
  ID: 32.a0.c7 (front door hds  grp:   1 type: CTRL  data: 0x10 0x11 0x45
  ID: 32.a0.c7 (front door hds  grp:   2 type: RESP  data: 0x00 0x00 0x02
  ID: 32.a0.c7 (front door hds  grp:   3 type: RESP  data: 0x00 0x00 0x00
  ID: 32.a0.c7 (front door hds  grp:   4 type: RESP  data: 0x00 0x00 0x00
  ID: 33.98.29 (back porch)     grp:   1 type: RESP  data: 0x01 0x20 0x45
  ID: 33.98.29 (back porch)     grp:   1 type: CTRL  data: 0x01 0x20 0x44
  ID: 36.81.0f (side door motio grp:   1 type: RESP  data: 0x10 0x11 0x45
  ID: 36.81.0f (side door motio grp:   2 type: RESP  data: 0x00 0x00 0x02
  ID: 36.81.0f (side door motio grp:   3 type: RESP  data: 0x00 0x00 0x03
  ID: 36.81.52 (driveway motion grp:   1 type: RESP  data: 0x10 0x11 0x45
  ID: 36.81.52 (driveway motion grp:   2 type: RESP  data: 0x00 0x00 0x02
  ID: 36.81.52 (driveway motion grp:   3 type: RESP  data: 0x00 0x00 0x03
  ID: 37.b2.9b (back door motio grp:   1 type: RESP  data: 0x10 0x11 0x45
  ID: 37.b2.9b (back door motio grp:   2 type: RESP  data: 0x00 0x00 0x02
  ID: 37.b2.9b (back door motio grp:   3 type: RESP  data: 0x00 0x00 0x03
  ID: 37.b2.a1 (living room mot grp:   1 type: RESP  data: 0x00 0x00 0x00
  ID: 37.b2.a1 (living room mot grp:   1 type: CTRL  data: 0x10 0x01 0x44
  ID: 37.b2.a1 (living room mot grp:   2 type: RESP  data: 0x00 0x00 0x02
  ID: 37.b2.a1 (living room mot grp:   3 type: RESP  data: 0x00 0x00 0x03
  ID: 39.20.d3                  grp:   0 type: RESP  data: 0x00 0x00 0x00
  ID: 39.a5.53 (living room lam grp:   1 type: RESP  data: 0x01 0x0e 0x41
  ID: 39.a5.53 (living room lam grp:   1 type: CTRL  data: 0x01 0x21 0x44
  ID: 3b.0e.f7 (unused micro di grp:   1 type: RESP  data: 0x01 0x35 0x48
  ID: 3b.0e.f7 (unused micro di grp:   1 type: CTRL  data: 0x01 0x35 0x48
  ID: 3d.f7.a1 (computer room)  grp:   1 type: CTRL  data: 0x01 0x20 0x45
  ID: 3d.f7.a1 (computer room)  grp:   1 type: RESP  data: 0x01 0x20 0x45
  ID: 3e.09.53 (stairs slave)   grp:   1 type: RESP  data: 0x00 0x00 0x00
  ID: 3e.09.53 (stairs slave)   grp:   1 type: CTRL  data: 0x01 0x20 0x45
  ID: 3e.11.14 (back porch eves grp:   1 type: RESP  data: 0x00 0x00 0x00
  ID: 3e.11.14 (back porch eves grp:   1 type: CTRL  data: 0x01 0x20 0x45
  ID: 3e.87.1f (living room bac grp:   1 type: CTRL  data: 0x01 0x0e 0x43
  ID: 3e.87.1f (living room bac grp:   1 type: RESP  data: 0x00 0x00 0x00
  ID: 3f.a0.8f (basement leak s grp:   1 type: RESP  data: 0x00 0x00 0x01
  ID: 3f.a0.8f (basement leak s grp:   1 type: CTRL  data: 0x10 0x08 0x44
  ID: 3f.a0.8f (basement leak s grp:   2 type: RESP  data: 0x10 0x08 0x44
  ID: 3f.a0.8f (basement leak s grp:   3 type: RESP  data: 0x00 0x00 0x03
  ID: 3f.a0.8f (basement leak s grp:   4 type: RESP  data: 0x00 0x00 0x04
  ID: 3f.bc.3e (hot water tank  grp:   1 type: CTRL  data: 0x10 0x08 0x44
  ID: 3f.bc.3e (hot water tank  grp:   1 type: RESP  data: 0x00 0x00 0x01
  ID: 3f.bc.3e (hot water tank  grp:   2 type: RESP  data: 0x10 0x08 0x44
  ID: 3f.bc.3e (hot water tank  grp:   3 type: RESP  data: 0x00 0x00 0x03
  ID: 3f.bc.3e (hot water tank  grp:   4 type: RESP  data: 0x00 0x00 0x04
  ID: 41.1a.eb (bub room)       grp:   1 type: RESP  data: 0x02 0x2a 0x45
  ID: 41.1a.eb (bub room)       grp:   1 type: CTRL  data: 0x01 0x20 0x45
  ID: 41.1a.ec (stairs)         grp:   1 type: RESP  data: 0x01 0x20 0x45
  ID: 41.1a.ec (stairs)         grp:   1 type: CTRL  data: 0x01 0x20 0x45
  ID: 41.81.d6 (basement door h grp:   1 type: RESP  data: 0x00 0x00 0x00
  ID: 41.81.d6 (basement door h grp:   1 type: CTRL  data: 0x10 0x11 0x45
  ID: 41.81.d6 (basement door h grp:   2 type: RESP  data: 0x00 0x00 0x02
  ID: 41.81.d6 (basement door h grp:   3 type: RESP  data: 0x00 0x00 0x03
  ID: 41.81.d6 (basement door h grp:   4 type: RESP  data: 0x00 0x00 0x04
  ID: 43.32.94 (dining room)    grp:   1 type: RESP  data: 0x01 0x20 0x45
  ID: 43.32.94 (dining room)    grp:   1 type: CTRL  data: 0x01 0x20 0x45
  ID: 43.3b.64 (attic)          grp:   1 type: RESP  data: 0x00 0x00 0x00
  ID: 43.3b.64 (attic)          grp:   1 type: CTRL  data: 0x01 0x20 0x45
  ID: 43.3d.2d (basement)       grp:   1 type: RESP  data: 0x00 0x00 0x00
  ID: 43.3d.2d (basement)       grp:   1 type: CTRL  data: 0x01 0x20 0x45
  ID: 43.3d.7b (toms closet)    grp:   1 type: RESP  data: 0x01 0x20 0x45
  ID: 43.3d.7b (toms closet)    grp:   1 type: CTRL  data: 0x01 0x20 0x45
  ID: 43.48.88 (outside front)  grp:   1 type: RESP  data: 0x00 0x00 0x00
  ID: 43.48.88 (outside front)  grp:   1 type: CTRL  data: 0x01 0x20 0x45
  ID: 44.f1.d3 (lauras closet)  grp:   1 type: RESP  data: 0x02 0x37 0x48
  ID: 44.f1.d3 (lauras closet)  grp:   1 type: CTRL  data: 0x01 0x20 0x45
  ID: 45.dd.64                  grp:   1 type: RESP  data: 0x00 0x00 0x00
  ID: 45.dd.64                  grp:   1 type: CTRL  data: 0x10 0x11 0x45
  ID: 45.dd.64                  grp:   2 type: RESP  data: 0x00 0x00 0x00
  ID: 45.dd.64                  grp:   3 type: RESP  data: 0x00 0x00 0x00
  ID: 45.dd.64                  grp:   4 type: RESP  data: 0x00 0x00 0x00
  ID: 46.05.ad (upstairs bathro grp:   1 type: RESP  data: 0x01 0x20 0x45
  ID: 46.05.ad (upstairs bathro grp:   1 type: CTRL  data: 0x02 0x2a 0x45
  ID: 4d.78.43 (living room lam grp:   1 type: RESP  data: 0x01 0x21 0x44
  ID: 4d.78.43 (living room lam grp:   1 type: CTRL  data: 0x01 0x21 0x44
  ID: 4d.c2.06 (unused micro on grp:   1 type: RESP  data: 0x01 0x20 0x45
  ID: 4d.c2.06 (unused micro on grp:   1 type: CTRL  data: 0x02 0x2f 0x48
  ID: 4e.0a.06 (unused on/off m grp:   1 type: RESP  data: 0x10 0x11 0x45
  ID: 4e.0a.06 (unused on/off m grp:   1 type: CTRL  data: 0x02 0x37 0x48
  ID: 4e.74.d0                  grp:   1 type: RESP  data: 0x00 0x00 0x00
  ID: 4e.74.d0                  grp:   1 type: CTRL  data: 0x02 0x38 0x43
  ID: 56.41.ab (living room lam grp:   1 type: RESP  data: 0x01 0x20 0x41
  ID: 56.41.ab (living room lam grp:   1 type: CTRL  data: 0x01 0x20 0x45
  ID: 8f.00.00                  grp:   1 type: RESP  data: 0x01 0x00 0x0
```

One device from my second floor is my computer room dimmer and it had a responder link to 0x1c in its db

```
DeviceDb: (delta 23)
  0fcf: 28.a4.22 (master bedroom  grp:   3 type: RESP data: 0x00 0x00 0x03
  0fd7: 40.d1.6e (modem)          grp:  28 type: RESP data: 0x00 0x1d 0x01
  0fdf: 40.d1.6e (modem)          grp:  26 type: RESP data: 0x00 0x00 0x1a
  0fe7: 40.d1.6e (modem)          grp:  21 type: RESP data: 0xff 0x01 0x01
  0fef: 40.d1.6e (modem)          grp:   7 type: RESP data: 0x00 0x00 0x07
  0ff7: 40.d1.6e (modem)          grp:   1 type: CTRL data: 0x03 0x1c 0x01
  0fff: 40.d1.6e (modem)          grp:   1 type: RESP data: 0xff 0x1c 0x01
Unused:
Last:
  0fc7: 00.00.00                  grp:   0 type: RESP data: 0x00 0x00 0x00 (UNUSED) (LAST)
GroupMap
  1 -> ['40.d1.6e (modem)']
```
In the openHAB native binding, this works with the current links.  Does the Insteon<->MQTT bridge require a modem controller link to this group to every device it is going to send the group broadcast to?
