### ISSUE TITLE
Setting up KPL "radio button" scene in scenes.yaml

### ISSUE THREAD

**Issue by MrGibbage** [TD22057/insteon-mqtt#328]
Would this be the correct way to set up a radio button scene on a KPL? Button 3 is the OFF button; the other buttons should turn off when it is pressed.

```
  - name: Fan Off
    responders:
      - family room kpl
        group: 4
        on_level: 0
      - family room kpl
        group: 5
        on_level: 0
      - family room kpl
        group: 6
        on_level: 0
      - family room fan
        on_level: 0
    controllers:
      - modem: 30
      - family room kpl: 3
```
Repeat accordingly for the LOW, MED and HIGH scenes

I tried it like that, and after restarting insteon-mqtt, it wrote "null" after some of the responders, so I am pretty sure I dorked it up.
