### ISSUE TITLE
Report state of a controller switch

### ISSUE THREAD

**Issue by yonigold1** [TD22057/insteon-mqtt#367]
So let's say I have Light A that is controlled by Dimmer A, I have Dimmer B on another wall that controls Light A through linking the 2 Dimmers together. My question/concern is when using Dimmer A to turn on the light it reports the state to Home Assistant but if I turn the light on through Dimmer B the state does not reflect in Home Assistant so now the question is, is there a way to make Dimmer A (or B I'm not sure which one should be responsible for this) report the correct state to Home Assistant?

Any help is appreciated :)

**Comment by krkeegan** [comment]
What I hear you saying it that you have your links configured like this:

```yaml
# Link 1
- controllers:
  - Dimmer A
- responders:
  - Light A
  - Dimmer B
# Link 2
- controllers:
  - Dimmer B
- responders:
  - Dimmer A
```
That shouldn't work within Insteon.  If those are the only links present, when you manually control `Dimmer B` only `Dimmer A` will respond but `Light A` will not do anything.

What you need is:
```yaml
# Link 1
- controllers:
  - Dimmer A
  - Dimmer B
- responders:
  - Light A
  - Dimmer A
  - Dimmer B
```
