### ISSUE TITLE
HA Discovery Scenes?

### ISSUE THREAD

**Issue by zimmer62** [TD22057/insteon-mqtt#396]
Wondering if scenes can also be discovered?

**Describe the solution you'd like**
I'd like to define named scenes in the scenes.yaml file and have those entities get created in home assistant automaticlly.

```
  - name: 'all living room lights'
    controllers:
      - modem: 21
    responders:
      - living room switch north
      - living room switch east
      - joes chair lamp
      - katies chair lamp
      - fireplace lamp
      - bar lamp
      
```
Then of course an mqtt device would get created named all living room lights.... in which would trigger the modem to send scene command 21 

**Describe alternatives you've considered**
Certainly scenes work as they did before discovery was added to insteon-mqtt, however adding them and keeping them in sync with the scenes.yaml would be ideal.
