### ISSUE TITLE
Possible breaking change in newer version

### ISSUE THREAD

**Issue by djfjeff** [TD22057/insteon-mqtt#425]
I possibly see a breaking change in newer version (don't really remember what version introduced this).

My keypad and remote now produce a MQTT message like this :
```
{ "state" : "OFF",
  "mode" : "NORMAL",
  "timestamp" : 1622078738,
  "reason" : "command" }
```

Instead of the previous message that was like this before :
```
OFF
```

Now, my automation for my keypad and remote are broken. For example, for my keypad :
```
- id: "kitchen_lights_on_automation"                          
  alias: "Kitchen Lights ON Automation"
  trigger:                                   
    platform: state
    entity_id: switch.hallway_keypad_button_3
    from: "off"                             
    to: "on"
  action:         
    service: script.kitchen_lights_on_script
```

And for my remote :
```
- id: "remote_button_1_automation"  
  alias: "Remote Button 1 Automation"
  trigger:                                    
    platform: mqtt                                            
    topic: "insteon/44.b4.06/state/1"             
  action:                            
    service_template: light.turn_{{ trigger.payload.lower() }}
    data:                                     
      entity_id: light.bedroom_light_2
```

I did not look to solve my issue yet but I thought to report this as a potential breaking change.

**Comment by krkeegan** [comment]
Yes, as of the 1.0.0 release the state payloads are all json in the default config.  However, this would only affect you if you do not have any payload specified in your config.yaml file.  This was not marked a breaking change because prior to version 1.0.0 the default config.yaml file specified these payloads.

You can revert back to the old style by adding the following to your config.yaml file:

```yaml
mqtt:
  switch:
    state_payload: {{on_str.upper()}}
  remote:
    state_payload: {{on_str.upper()}}
```
