### ISSUE TITLE
Motion Sensor Dawn/Dusk Reversed

### ISSUE THREAD

**Issue by EnGamma** [TD22057/insteon-mqtt#511]
**Describe the bug**
Motion sensor reports of dawn/dusk are reversed.

**To Reproduce**
1. Put the motion sensor in the dark and dawn/dusk state reports is_dusk=0, is_dawn=1; 
2. Put it in bright light and is_dusk=1, is_dawn=0
3.  e.g., mqtt dawn topic/payload 
a. with device under bright light:
insteon/ms_i_b/dawn { "name" : "ms_i_b",
  "addr" : "31.7d.29",
  "msg" : "[insteon, ms_i_b, state, is_dawn] => 0",
  "msg_min" : "[state, is_dawn] => 0",
  "dawndusk" : "dusk",
  "is_dawn" : "0",
  "is_dusk" : "1",
  "state"    : "OFF",
  "state_lc" : "off",
  "timestamp" : 1680919193 }
b. with device in a dark box:
insteon/ms_i_b/dawn { "name" : "ms_i_b",
  "addr" : "31.7d.29",
  "msg" : "[insteon, ms_i_b, state, is_dawn] => 1",
  "msg_min" : "[state, is_dawn] => 1",
  "dawndusk" : "dawn",
  "is_dawn" : "1",
  "is_dusk" : "0",
  "state"    : "ON",
  "state_lc" : "on",
  "timestamp" : 1680919648 }

5. I have about a dozen motion sensors that are producing the same result.

**Expected behavior**
Logical inverse of the reported dawn/dusk state

**Your Configuration**
What are the relevant entries in your config.yaml?  Please include the device definition of the device affected.
```yaml
# Put your relevant config.yaml text below this line
 motion:
    #------------------------------------------------------------------------
    # Motion sensors
    #------------------------------------------------------------------------

    # Motion sensors will use the state and low battery configuration
    # inputs from battery_sensor and some sensors add an addition
    # dawn/dusk notification which is configured here.

    # Output dawn/dusk change topic and payload.  This message is sent
    # whenever the device light sensor detects dawn or dusk changes.
    # Available variables for templating are:
    #   address = 'aa.bb.cc'
    #   timestamp = the current timestamp
    #   name = 'device name'
    #   is_dawn = 0/1
    #   is_dawn_str = 'off'/'on'
    #   is_dusk = 0/1
    #   is_dusk_str = 'off'/'on'
    #   state = 'dawn'/'dusk' #FIXME state is not reporting dawn/dusk
    dawn_dusk_topic: 'insteon/{{name}}/dawn'
    dawn_dusk_payload: >-
      { "name" : "{{name}}",
        "addr" : "{{address}}",
        "msg" : "[insteon, {{name}}, state, is_dawn] => {{is_dawn}}",
        "msg_min" : "[state, is_dawn] => {{is_dawn}}",
        "dawndusk" : "{{state}}",
        "state"    : "{{is_dawn_str.upper()}}",
        "state_lc" : "{{is_dawn_str.lower()}}",
        "timestamp" : {{timestamp}} }


```

**Hardware Details**
- Debian on Raspberry Pi 4
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian

- The model of your Modem, see https://github.com/TD22057/insteon-mqtt/blob/master/docs/mqtt.md#get-device-model-information
```txt
# Please paste the output of get-model for the modem below this line
2023-04-08 01:47:41.769 UI Mqtt: Commanding Modem device 3d.9a.1c (modem) cmd=get_model
2023-04-08 01:47:41.769 UI Modem: Modem 3d.9a.1c model information: NETWORK_BRIDGES (0x03): '2413U' (0x15) 'PowerLinc USB Modem (Dual Band)'
2023-04-08 01:47:41.770 UI Mqtt: Success get_model
2
```

- The model of the affected Device, see https://github.com/TD22057/insteon-mqtt/blob/master/docs/mqtt.md#get-device-model-information
```txt
# Please paste the output of get-model for the affected device below this line

2023-04-08 01:54:22.143 UI Base: Device 31.7d.29 received model information: CONTROLLERS (0x00): 'Unknown' (0x01) firmware: 0x41

```

**Additional context**
Running insteon-mqtt 1.1.1 in a docker container
