### ISSUE TITLE
Example configuration.yaml for Home Assistant

### ISSUE THREAD

**Issue by jtmoderate876** [TD22057/insteon-mqtt#67]
Todd (or anyone), Can you provide an example of configuration.yaml for Home Assistant that works with this insteon-mqtt?

Background:

I found your insteon-mqtt last weekend and was able to quickly get it working with Node-RED...

but to better understand it and the various MQTT topics, I tried home assistant with it this weekend...

so I am brand new to both. 

Thx.

**Comment by jtmoderate876** [comment]
Nevermind, you have provided what I am looking for here:
https://github.com/TD22057/insteon-mqtt/blob/master/config.yaml

Please close.

**Comment by TD22057** [comment]
See config.yaml for examples.

**Comment by jtmoderate876** [comment]
I think it turns out that the config.yaml examples are for the insteon-mqtt side and not Home Assistant.
Can someone provide complementary Home Assistant configuration.yaml examples?

**Comment by larizzo** [comment]
You should look a little more closely in config.yaml:
`  # On/Off switch.  Non-dimming lamp modules and wall switches.
  # In Home Assistant use MQTT switch with a configuration like:
  #   switch:
  #     - platform: mqtt
  #       state_topic: 'insteon/aa.bb.cc/state'
  #       command_topic: 'insteon/aa.bb.cc/set'`

**Comment by jtmoderate876** [comment]
Thanks @larizzo .
That works for switch. I can't figure out dimmer (or light, perhaps).
Also, do I have to manually enter EVERY device in my house or can Home Assistant "discover" my insteon-mqtt?

**Comment by larizzo** [comment]
The dimmer section is also in the config.yaml:
```
  # Dimmer switch.  Dimming lamp modules and wall switches.  In Home
  # Assistant use MQTT light with a configuration like the following -
  # this gets HA to send the brightness value as the payload for all
  # control of the light.
  #   light:
  #     - platform: mqtt_json
  #       name: "insteon 1"
  #       state_topic: "insteon/48.b0.ad/state"
  #       command_topic: "insteon/48.b0.ad/level"
  #       brightness: true
```
yes you have to set one for each switch/plug etc... like this:
```
light:
- platform: mqtt_json
  name: "Dinette"
  state_topic: "insteon/6c.fg.54/state"
  command_topic: "insteon/6c.fg.54//level"
  brightness: true

- platform: mqtt_json
  name: "Entrance"
  state_topic: 'insteon/3d.9f.f9/state'
  command_topic: "insteon/3d.9f.f9/level"
  brightness: true
```
